version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  post_build:
    commands:
      - mvn package
      - mv target/petstore.war petstore.war
artifacts:
  files:
    - petstore.war
    - .ebextensions/**/*
